Add API files
sbgisen/kachaka-api-for-openrmf pull request #1
Opened 2024-03-25 03:01 UTC by h-wata

## Summary
OpenRMFに対応するためのFileを追加。

- fix #

## Detail
- Zenohとの接続するためのファイルを追加
- REST APIファイルを追加
- README.mdをアップデート

## Impact

## Test

## Attention

関連PR：　https://github.com/sbgisen/fleet_adapter_for_kachaka/pull/1

2024-03-26 07:12 UTC, MikhailBertrand commented on Pipfile
> +kachaka-api = {editable = true, path = "./kachaka-api"}
ここで記載されているライブラリ一覧はどこから持ってきて何で使われているものですか？

2024-03-26 09:49 UTC, MikhailBertrand requested changes

2024-03-26 09:49 UTC, MikhailBertrand commented on .gitignore
> +kachaka_api_pb2*
自動生成される`Pipfile.lock`も加えておきましょう

2024-03-26 09:49 UTC, MikhailBertrand commented on Pipfile
> +kachaka-api = {editable = true, path = "./kachaka-api"}
以下の行も追加してREADMEからステップを取り除きましょう
```
eclipse-zenoh = "*"
```

2024-03-26 09:49 UTC, MikhailBertrand commented on README.md
> +   ```
別コメント参照

2024-03-26 09:52 UTC, MikhailBertrand commented on .gitignore
> +kachaka_api_pb2*
寧ろtrackした方が良いらしいです。

2024-03-27 01:45 UTC, h-wata commented on Pipfile
> +kachaka-api = {editable = true, path = "./kachaka-api"}
自分の環境だと下記エラーが出るんですが、ここにあるように`pipenv lock --pre`は実行しました？
```
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠼ Locking...False
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement eclilpse-zenoh (from versions: none)
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 918, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 691, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 448, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for eclilpse-zenoh

Traceback (most recent call last):
  File "/home/gisen/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 164, in do_install
    do_init(
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 672, in do_init
    do_lock(
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 859, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/home/gisen/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 728, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```

2024-03-27 01:48 UTC, h-wata commented on Pipfile
> +kachaka-api = {editable = true, path = "./kachaka-api"}
typoでした。できました。

2024-03-27 02:25 UTC, h-wata commented on README.md
> +   ```
追加しました。

2024-03-27 02:26 UTC, h-wata commented on .gitignore
> +kachaka_api_pb2*
[1c1705f](https://github.com/sbgisen/kachaka-api-for-openrmf/pull/1/commits/1c1705f65de648f9e27036c3bed7b2eb32da05c2)追加しました。

2024-03-27 02:26 UTC, h-wata commented on Pipfile
> +kachaka-api = {editable = true, path = "./kachaka-api"}
[1c1705f](https://github.com/sbgisen/kachaka-api-for-openrmf/pull/1/commits/1c1705f65de648f9e27036c3bed7b2eb32da05c2)追加しました。

2024-03-27 03:13 UTC, MikhailBertrand commented on README.md
> +   ```
なんかリセットした後でこれが失敗するタイミングがありました。
アップデートされたPipfileを用いてインストールを行った直後です。
```
$ pipenv run python -m grpc_tools.protoc -I kachaka-api/protos --python_out=. --grpc_python_out=. kachaka-api/protos/kachaka-api.proto
/home/gisen/.local/share/virtualenvs/kachaka-api-for-openrmf-JuejO7n2/bin/python: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
```

2024-03-27 03:16 UTC, MikhailBertrand commented on README.md
> +   ```
1度発生しただけでリセットしてやり直しても再発しないのでコメントだけ残して閉じておきます。

2024-04-03 06:13 UTC, MikhailBertrand approved these changes

2024-04-03 06:13 UTC, merged