Hotfix/refactor
sbgisen/kachaka-api-for-openrmf pull request #2
Opened 2024-03-27 10:25 UTC by MikhailBertrand

## Summary

微細なコード修正と本リポジトリの用途を明確化するためのセットアッププロセスの追加
本リポジトリは主に

- 最終的にカチャカ内部で立ち上げるためのスクリプトを管理
- 上記のようなものを正しくセットアップするためのスクリプトを管理
- 開発者向けのpipenv環境を用意

するのを主な目的とすることを推奨

## Detail

- コード修正
  - リファクタリング
  - 一般的なREST APIの慣習に沿い、環境変数によりターゲットとなるIPとポートを指定し、実行行を外した
- カチャカ側において、起動時にREST API サーバーが立ち上がるように設定するためのスクリプトを追加
- 開発者向けpipenv環境のセットアップをするためのスクリプトを追加
- 以上に伴うREADMEの整備

※ Zenoh機能についてはドラフト解除までにまとめる予定

2024-03-29 01:01 UTC, h-wata requested changes

2024-03-29 01:01 UTC, h-wata commented on README.md
> +pipenv run python /path/to/kachaka-api-for-openrmf/scripts/connect_openrmf_by_zenoh.py
環境変数で指定するのは異論ないのですが、引数は引数で指定できるように残したいのですがいかがでしょう。
変数名がわからなくなったときにhelpで参照できますし、PRなどの動作確認時に毎回SSHで入らなくともよくなるので。
引数指定がなかった場合は環境変数を見るような挙動が良いように感じますがいかがでしょう？

2024-03-29 01:04 UTC, MikhailBertrand commented on README.md
> +PYTHONPATH="/home/gisen/work/kachaka-api-for-openrmf/scripts:$PYTHONPATH" pipenv run uvicorn rest_kachaka_api:app --host 0.0.0.0 --port 26502
見逃していました

2024-03-29 01:10 UTC, MikhailBertrand commented on README.md
> +pipenv run python /path/to/kachaka-api-for-openrmf/scripts/connect_openrmf_by_zenoh.py
いや、ここはややこしくしないために環境変数に統一した方が良いと思います。

ここでの実行方法は本来の用途（カチャカ体内での起動）とは異なる使い方であり、本来の用途に合わせて統一するべきです。
実際Zenohノードの起動に関しては環境変数でも引数でもどちらでも良いのですがuvicornで起動するREST APIサーバーに関しては環境変数による指定が一般的とされています。
なので、カチャカ体内で起動するスクリプトに関しては環境変数利用に統一した方が明瞭だと考えます。

2024-03-29 01:29 UTC, MikhailBertrand commented on README.md
> +pipenv run python /path/to/kachaka-api-for-openrmf/scripts/connect_openrmf_by_zenoh.py
AIとも相談しましたが、現状過度に複雑な引数を指定しているわけではなく、かつやはり環境変数で最初に必要なパラメータを指定してあげるのがインラインで引数を指定するよりも見やすいので、一旦環境変数利用に統一した方が良さそうです。

2024-03-29 05:24 UTC, h-wata commented on README.md
> +pipenv run python /path/to/kachaka-api-for-openrmf/scripts/connect_openrmf_by_zenoh.py
承知しました。

2024-04-03 03:03 UTC, MikhailBertrand commented
少しzenoh通信用スクリプトのasync周りの実装で気になるところがあったのですが、修正したポイントの動作確認をする環境が今手元に無いのでここまでの変更部分の確認をお願いします。

2024-04-03 05:27 UTC, h-wata approved these changes

2024-04-03 05:27 UTC, merged