Fix zenoh topic name
sbgisen/kachaka-api-for-openrmf pull request #7
Opened 2024-05-10 08:51 UTC by h-wata

## Summary
https://github.com/sbgisen/zenoh_bridge/pull/1 に合わせてTopci名やタスクの管理方法などを修正。

- fix #

## Detail

## Impact

## Test

## Attention

2024-05-15 01:54 UTC, h-wata commented
/review

2024-05-15 01:56 UTC, h-wata commented
/suggestion

2024-05-15 03:24 UTC, MikhailBertrand requested changes

2024-05-15 03:24 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +        print(file_path)
デバッグ用のprint文でしょうか？必要なければ消してください。
利用するファイル名を表示したいのであればそういうメッセージにした方が良いです。
`print(f'Using file: {file_path}')`など。

2024-05-15 03:24 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
config.yamlは使用方法に応じて変更されうるファイルですよね？
であればここは固定パスにせずに、インスタンス初期化時の引数で渡した方が良いです。

2024-05-17 02:24 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
慣習的な話で、変更要請ではないただのコメントなのですが、`yaml.safe_load(f)` にする方が、悪意あるファイルのロードを弾いてくれて一般的には安全とされています。
`FullLoader`は怪しげなyamlファイルの存在がありえない場合にだけ使うイメージです。

2024-05-17 02:30 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
よく見たらすでに自動提案されていましたね。さすがAI。

2024-05-17 02:31 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
逆のこと言ってないか…？僕の認識が間違っている…？

2024-05-17 02:34 UTC, h-wata commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
AIに言われて直してしまいました笑

2024-05-17 02:35 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
明らかにAIが間違ったこと言ってますねこれ…。
https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html

2024-05-17 02:39 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
ChatGPTくん…。
![image](https://github.com/sbgisen/kachaka-api-for-openrmf/assets/50670249/d99ece4f-4497-4c82-8b4f-4098c157609b)

2024-05-17 02:49 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
![image](https://github.com/sbgisen/kachaka-api-for-openrmf/assets/50670249/370fcc36-817e-43e9-b523-c4620b739133)

2024-05-17 02:52 UTC, MikhailBertrand commented on scripts/connect_openrmf_by_zenoh.py
> +            config = yaml.load(f, Loader=yaml.FullLoader)
safe_loadで行きましょう。

2024-05-17 06:13 UTC, MikhailBertrand commented
> publish_resultメソッドにおいて、resのデータ構造が期待通りでない場合に単にログを出力していますが、この部分で例外を投げるか、エラー状態を適切にハンドルすることを検討してください。これにより、エラーが発生した際のロバスト性が向上します。

上で指摘されている箇所は修正かけても良いと思いますがいかがですか？

2024-05-17 09:50 UTC, MikhailBertrand approved these changes

2024-05-17 09:50 UTC, merged